page1 <- grid.arrange(plot_vec[[1]],
                      plot_vec[[2]],
                      plot_vec[[3]],
                      plot_vec[[4]],
                      plot_vec[[5]],
                      plot_vec[[6]],
                      plot_vec[[7]],
                      plot_vec[[8]],
                      plot_vec[[9]],
                      ncol = 3, nrow = 3)

page2 <- grid.arrange(plot_vec[[10]],
                      plot_vec[[11]],
                      plot_vec[[12]],
                      plot_vec[[13]],
                      plot_vec[[14]],
                      plot_vec[[15]],
                      plot_vec[[16]],
                      plot_vec[[17]],
                      plot_vec[[18]],
                      ncol = 3, nrow = 3)

page3 <- grid.arrange(plot_vec[[19]],
                      plot_vec[[20]],
                      plot_vec[[21]],
                      plot_vec[[22]],
                      plot_vec[[23]],
                      plot_vec[[24]],
                      plot_vec[[25]],
                      plot_vec[[26]],
                      plot_vec[[27]],
                      ncol = 3, nrow = 3)
page4 <- grid.arrange(plot_vec[[28]],
                      plot_vec[[29]],
                      plot_vec[[30]],
                      plot_vec[[31]],
                      plot_vec[[32]],
                      plot_vec[[33]],
                      plot_vec[[34]],
                      ncol = 3, nrow = 3)